# Generated by Django 4.1.7 on 2023-05-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["product_name"]},
        ),
        migrations.AlterModelOptions(
            name="productphoto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["store_name"]},
        ),
        migrations.AlterModelOptions(
            name="storelink",
            options={"ordering": ["pk"]},
        ),
    ]
