name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PROJECT_ROOT: ${{ github.workspace }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: check things
        run: ls $PROJECT_ROOT
        echo: true
      - name: Install dependencies
        run: |
          cd $PROJECT_ROOT/web/selecto
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd web/selecto
          pytest
